name: Project CI

on: [push]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies (Build Step 1)
        run: npm install
        
      - name: Run Build Script (Build Step 2)
        run: npm run build
        
      - name: Run Logic Tests (Test Step)
        run: npm test
